import React from 'react';
import Menu from '../../components/Menu'

const userList = [
  "ACERO GARCIA, SAMUEL",
  "ALJURI MARTINEZ, DAREK",
  "CEPEDA URIBE, JUAN FELIPE",
  "CHAVES PEREZ, ANA MARIA",
  "CRUZ PAVAS, CARLOS DAVID",
  "DIAZ ALGARIN, DIEGO NORBERTO",
  "DIAZ BERNAL, JORGE ESTEBAN",
  "DIAZ VARGAS, DAVID ESTEBAN",
  "FORERO PEÑA, JUAN JOSE",
  "GUTIERREZ DE PIÑERES BARBOSA, SANTIAGO",
  "LOPEZ HUERTAS, SAMUEL ESTEBAN",
  "MEDINA FERNANDEZ, MICHAEL STEVEN",
  "MORENO CARVAJAL, KATHERIN JULIANA",
  "MORENO PATARROYO, JUAN PABLO",
  "MUÑOZ SENDOYA, NICOLAS ESTEBAN",
  "NAVARRO CUY, SANTIAGO",
  "PARRADO MORALES, JUAN PABLO",
  "RAMIREZ CHINCHILLA, DANIEL SANTIAGO",
  "RESTREPO COCA, JUAN PABLO",
  "REYES GONZALEZ, GABRIELA",
  "RODRIGUEZ FALLA, JUAN JOSE",
  "RUIZ TORRES, VALENTINA",
  "SALAS GUTIERREZ, MARIANA",
  "SANCHEZ SANDOVAL, SEBASTIAN",
  "SARMIENTO GUARNIZO, JOSUE DAVID",
  "SOLER PRADO, SANTIAGO",
  "TAMAYO LOPEZ, MARIA FERNANDA",
  "URREA LARA, DEIVID NICOLAS",
  "AZCONA, ANDRÉS"
];

const Contacts = () => {
  return (
    <div>
      <h1>Contacts</h1>
      <pre>{JSON.stringify(userList, null, 2).slice(1, -1)}</pre>
      <Menu page={"contacts"} />
    </div>
  );
};

export default Contacts;